using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace SBuild.Compilation;

/// <summary>
/// Produces the implicit global usings, the same set the .NET SDK adds for <c>Microsoft.NET.Sdk</c> projects.
/// </summary>
public static class ImplicitUsingsGenerator
{
    /// <summary>
    /// Namespaces imported globally when implicit usings are enabled.
    /// </summary>
    public static IReadOnlyList<string> Namespaces { get; } =
    [
        "System",
        "System.Collections.Generic",
        "System.IO",
        "System.Linq",
        "System.Net.Http",
        "System.Threading",
        "System.Threading.Tasks"
    ];

    /// <summary>
    /// Text of the generated file.
    /// </summary>
    public static string GenerateSource()
    {
        var sb = new StringBuilder("// <auto-generated/>").AppendLine();
        foreach (var ns in Namespaces)
        {
            sb.Append("global using global::").Append(ns).AppendLine(";");
        }

        return sb.ToString();
    }

    internal static SyntaxTree CreateSyntaxTree(CSharpParseOptions parseOptions) =>
        CSharpSyntaxTree.ParseText(GenerateSource(), parseOptions, "SBuild.ImplicitUsings.g.cs", Encoding.UTF8);
}
